import "~/styles/globals.css";
import { TopNav } from "~/app/_components/topnav";

import { ClerkProvider } from "@clerk/nextjs";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Gallery App",
  description: "Generated by Danindu Nawarathna",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className={"${inter.variable} flex flex-col gap-4 font-sans"}>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
